services:
  postgres:
    image: postgres:16
    container_name: taskflow_db
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: taskflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:      
  postgres_data:
